import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { AppKit } from "@/connection";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppKit>
      <body
        className={`dark ${inter.className} antialiased min-h-screen bg-black bg-gradient-to-b from-black to-gray-900`}
      >
        {children}
      </body>
      </AppKit>
    </html>
  );
}
